// src/angular-frontend/src/app/components/header/header.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { AuthService } from '../../services/auth.service';
import { User } from '../../models/recipe.model';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent {
  @Input() currentView: string = 'home';
  @Output() uploadClick = new EventEmitter<void>();
  @Output() homeClick = new EventEmitter<void>();
  @Output() loginClick = new EventEmitter<void>();
  @Output() logoutClick = new EventEmitter<void>();

  currentUser: User | null = null;

  constructor(public authService: AuthService) {
    this.authService.currentUser$.subscribe(user => {
      this.currentUser = user;
    });
  }

  onUploadClick() {
    this.uploadClick.emit();
  }

  onHomeClick() {
    this.homeClick.emit();
  }

  onLoginClick() {
    this.loginClick.emit();
  }

  onLogoutClick() {
    this.logoutClick.emit();
  }
}

<header class="bg-white shadow-sm sticky top-0 z-50">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center h-16">
      <!-- Logo -->
      <div class="flex items-center cursor-pointer" (click)="onHomeClick()">
        <svg class="w-8 h-8 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253">
          </path>
        </svg>
        <h1 class="ml-2 text-2xl text-gray-900">Culina</h1>
      </div>

      <!-- Navigation -->
      <div class="flex items-center gap-4">
        <button 
          (click)="onUploadClick()"
          class="flex items-center gap-2 px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700 transition-colors">
          <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
          </svg>
          <span>Rezept hochladen</span>
        </button>

        <!-- User Menu -->
        <div *ngIf="currentUser; else loginButton">
          <div class="flex items-center gap-3">
            <img [src]="currentUser.avatar" [alt]="currentUser.name" class="w-10 h-10 rounded-full">
            <div class="flex flex-col">
              <span class="text-sm">{{ currentUser.name }}</span>
              <button (click)="onLogoutClick()" class="text-xs text-orange-600 hover:text-orange-700 text-left">
                Abmelden
              </button>
            </div>
          </div>
        </div>

        <ng-template #loginButton>
          <button 
            (click)="onLoginClick()"
            class="px-4 py-2 text-orange-600 border border-orange-600 rounded-lg hover:bg-orange-50 transition-colors">
            Anmelden
          </button>
        </ng-template>
      </div>
    </div>
  </div>
</header>

// src/components/Header.tsx
import { ChefHat, Upload, LogOut, User as UserIcon } from 'lucide-react';
import { Button } from './ui/button';
import { Avatar, AvatarFallback, AvatarImage } from './ui/avatar';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from './ui/dropdown-menu';
import type { User } from '../App';

type HeaderProps = {
  currentUser: User | null;
  onLoginClick: () => void;
  onRegisterClick: () => void;
  onLogout: () => void;
  onLogoClick: () => void;
  onUploadClick: () => void;
};

export function Header({
  currentUser,
  onLoginClick,
  onRegisterClick,
  onLogout,
  onLogoClick,
  onUploadClick,
}: HeaderProps) {
  return (
    <header className="sticky top-0 z-50 bg-white/80 backdrop-blur-md border-b border-orange-100 shadow-sm">
      <div className="container mx-auto px-4 py-4">
        <div className="flex items-center justify-between">
          <button
            onClick={onLogoClick}
            className="flex items-center gap-2 hover:opacity-80 transition-opacity"
          >
            <div className="bg-gradient-to-br from-orange-500 to-amber-600 p-2 rounded-xl">
              <ChefHat className="size-6 text-white" />
            </div>
            <span className="text-orange-600">Culina</span>
          </button>

          <div className="flex items-center gap-3">
            <Button
              onClick={onUploadClick}
              className="bg-gradient-to-r from-orange-500 to-amber-600 hover:from-orange-600 hover:to-amber-700"
            >
              <Upload className="size-4 mr-2" />
              Rezept hochladen
            </Button>

            {currentUser ? (
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button variant="ghost" className="relative h-10 w-10 rounded-full">
                    <Avatar>
                      <AvatarImage src={currentUser.avatar} alt={currentUser.name} />
                      <AvatarFallback>{currentUser.name.charAt(0)}</AvatarFallback>
                    </Avatar>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end" className="w-56">
                  <div className="flex items-center gap-2 p-2">
                    <Avatar className="h-8 w-8">
                      <AvatarImage src={currentUser.avatar} alt={currentUser.name} />
                      <AvatarFallback>{currentUser.name.charAt(0)}</AvatarFallback>
                    </Avatar>
                    <div className="flex flex-col">
                      <span className="text-sm">{currentUser.name}</span>
                      <span className="text-xs text-muted-foreground">{currentUser.email}</span>
                    </div>
                  </div>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem onClick={onUploadClick}>
                    <Upload className="size-4 mr-2" />
                    Rezept hochladen
                  </DropdownMenuItem>
                  <DropdownMenuItem onClick={onLogout}>
                    <LogOut className="size-4 mr-2" />
                    Abmelden
                  </DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            ) : (
              <>
                <Button variant="ghost" onClick={onLoginClick}>
                  Anmelden
                </Button>
                <Button
                  onClick={onRegisterClick}
                  variant="outline"
                  className="border-orange-300 text-orange-600 hover:bg-orange-50"
                >
                  Registrieren
                </Button>
              </>
            )}
          </div>
        </div>
      </div>
    </header>
  );
}
