// src/angular-frontend/src/app/components/login-dialog/login-dialog.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login-dialog',
  templateUrl: './login-dialog.component.html',
  styleUrls: ['./login-dialog.component.css']
})
export class LoginDialogComponent {
  @Output() close = new EventEmitter<void>();
  @Output() loginSuccess = new EventEmitter<void>();
  @Output() switchToRegister = new EventEmitter<void>();

  email = '';
  password = '';
  submitting = false;
  error: string | null = null;

  constructor(private authService: AuthService) {}

  onSubmit() {
    if (!this.email || !this.password) {
      this.error = 'Bitte fülle alle Felder aus.';
      return;
    }

    this.submitting = true;
    this.error = null;

    this.authService.login(this.email, this.password).subscribe({
      next: (response) => {
        if (response.success) {
          this.loginSuccess.emit();
        } else {
          this.error = response.message;
        }
        this.submitting = false;
      },
      error: (error) => {
        console.error('Login-Fehler:', error);
        this.error = error.error?.message || 'Login fehlgeschlagen. Bitte versuche es erneut.';
        this.submitting = false;
      }
    });
  }

  onClose() {
    this.close.emit();
  }

  onSwitchToRegister() {
    this.switchToRegister.emit();
  }

  onBackdropClick(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      this.onClose();
    }
  }
}

<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50" (click)="onBackdropClick($event)">
  <div class="bg-white rounded-lg shadow-xl w-full max-w-md mx-4 p-8">
    <!-- Header -->
    <div class="flex justify-between items-center mb-6">
      <h2 class="text-2xl text-gray-900">Anmelden</h2>
      <button 
        (click)="onClose()"
        class="text-gray-400 hover:text-gray-600">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
        </svg>
      </button>
    </div>

    <!-- Error Message -->
    <div *ngIf="error" class="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg">
      <p class="text-sm text-red-800">{{ error }}</p>
    </div>

    <!-- Form -->
    <form (ngSubmit)="onSubmit()">
      <div class="mb-4">
        <label class="block text-sm text-gray-700 mb-2">E-Mail</label>
        <input
          type="email"
          [(ngModel)]="email"
          name="email"
          required
          placeholder="deine@email.com"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
      </div>

      <div class="mb-6">
        <label class="block text-sm text-gray-700 mb-2">Passwort</label>
        <input
          type="password"
          [(ngModel)]="password"
          name="password"
          required
          placeholder="••••••••"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
      </div>

      <button
        type="submit"
        [disabled]="submitting"
        class="w-full px-6 py-3 bg-orange-600 text-white rounded-lg hover:bg-orange-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors mb-4">
        {{ submitting ? 'Wird angemeldet...' : 'Anmelden' }}
      </button>

      <p class="text-center text-sm text-gray-600">
        Noch kein Konto?
        <button
          type="button"
          (click)="onSwitchToRegister()"
          class="text-orange-600 hover:text-orange-700 ml-1">
          Jetzt registrieren
        </button>
      </p>
    </form>
  </div>
</div>

// src/components/LoginDialog.tsx
import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { ChefHat } from 'lucide-react';

type LoginDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onLogin: (email: string, password: string) => void;
  onSwitchToRegister: () => void;
};

export function LoginDialog({ open, onOpenChange, onLogin, onSwitchToRegister }: LoginDialogProps) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!email || !password) {
      alert('Bitte fülle alle Felder aus');
      return;
    }

    setIsLoading(true);

    // Simuliert Ajax Login Request zum PHP Backend
    console.log('Ajax Login Request würde an PHP Backend gesendet:', { email, password });
    
    // Simuliert Verzögerung
    await new Promise(resolve => setTimeout(resolve, 500));
    
    onLogin(email, password);
    setIsLoading(false);
    setEmail('');
    setPassword('');
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <div className="flex justify-center mb-4">
            <div className="bg-gradient-to-br from-orange-500 to-amber-600 p-3 rounded-xl">
              <ChefHat className="size-8 text-white" />
            </div>
          </div>
          <DialogTitle className="text-center">Willkommen zurück!</DialogTitle>
          <DialogDescription className="text-center">
            Melde dich an, um Rezepte hochzuladen und zu bewerten
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4 mt-4">
          <div>
            <Label htmlFor="login-email">E-Mail</Label>
            <Input
              id="login-email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="deine@email.de"
              required
            />
          </div>

          <div>
            <Label htmlFor="login-password">Passwort</Label>
            <Input
              id="login-password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="••••••••"
              required
            />
          </div>

          <Button
            type="submit"
            disabled={isLoading}
            className="w-full bg-gradient-to-r from-orange-500 to-amber-600 hover:from-orange-600 hover:to-amber-700"
          >
            {isLoading ? 'Anmelden...' : 'Anmelden'}
          </Button>
        </form>

        <div className="text-center text-sm text-gray-600 mt-4">
          Noch kein Konto?{' '}
          <button
            type="button"
            onClick={onSwitchToRegister}
            className="text-orange-600 hover:underline"
          >
            Jetzt registrieren
          </button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
