// src/components/RegisterDialog.tsx
import { useState } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { ChefHat } from 'lucide-react';

type RegisterDialogProps = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onRegister: (name: string, email: string, password: string) => void;
  onSwitchToLogin: () => void;
};

export function RegisterDialog({ open, onOpenChange, onRegister, onSwitchToLogin }: RegisterDialogProps) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!name || !email || !password || !confirmPassword) {
      alert('Bitte fülle alle Felder aus');
      return;
    }

    if (password !== confirmPassword) {
      alert('Passwörter stimmen nicht überein');
      return;
    }

    if (password.length < 6) {
      alert('Passwort muss mindestens 6 Zeichen lang sein');
      return;
    }

    setIsLoading(true);

    // Simuliert Ajax Register Request zum PHP Backend
    console.log('Ajax Register Request würde an PHP Backend gesendet:', { name, email, password });
    
    // Simuliert Verzögerung
    await new Promise(resolve => setTimeout(resolve, 500));
    
    onRegister(name, email, password);
    setIsLoading(false);
    setName('');
    setEmail('');
    setPassword('');
    setConfirmPassword('');
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <div className="flex justify-center mb-4">
            <div className="bg-gradient-to-br from-orange-500 to-amber-600 p-3 rounded-xl">
              <ChefHat className="size-8 text-white" />
            </div>
          </div>
          <DialogTitle className="text-center">Bei Culina registrieren</DialogTitle>
          <DialogDescription className="text-center">
            Erstelle einen Account und werde Teil unserer Koch-Community
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4 mt-4">
          <div>
            <Label htmlFor="register-name">Name</Label>
            <Input
              id="register-name"
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              placeholder="Dein Name"
              required
            />
          </div>

          <div>
            <Label htmlFor="register-email">E-Mail</Label>
            <Input
              id="register-email"
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="deine@email.de"
              required
            />
          </div>

          <div>
            <Label htmlFor="register-password">Passwort</Label>
            <Input
              id="register-password"
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="••••••••"
              required
            />
          </div>

          <div>
            <Label htmlFor="register-confirm-password">Passwort bestätigen</Label>
            <Input
              id="register-confirm-password"
              type="password"
              value={confirmPassword}
              onChange={(e) => setConfirmPassword(e.target.value)}
              placeholder="••••••••"
              required
            />
          </div>

          <Button
            type="submit"
            disabled={isLoading}
            className="w-full bg-gradient-to-r from-orange-500 to-amber-600 hover:from-orange-600 hover:to-amber-700"
          >
            {isLoading ? 'Registrieren...' : 'Registrieren'}
          </Button>
        </form>

        <div className="text-center text-sm text-gray-600 mt-4">
          Bereits registriert?{' '}
          <button
            type="button"
            onClick={onSwitchToLogin}
            className="text-orange-600 hover:underline"
          >
            Jetzt anmelden
          </button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

// src/angular-frontend/src/app/components/register-dialog/register-dialog.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-register-dialog',
  templateUrl: './register-dialog.component.html',
  styleUrls: ['./register-dialog.component.css']
})
export class RegisterDialogComponent {
  @Output() close = new EventEmitter<void>();
  @Output() registerSuccess = new EventEmitter<void>();
  @Output() switchToLogin = new EventEmitter<void>();

  name = '';
  email = '';
  password = '';
  confirmPassword = '';
  submitting = false;
  error: string | null = null;

  constructor(private authService: AuthService) {}

  onSubmit() {
    // Validierung
    if (!this.name || !this.email || !this.password || !this.confirmPassword) {
      this.error = 'Bitte fülle alle Felder aus.';
      return;
    }

    if (this.password !== this.confirmPassword) {
      this.error = 'Passwörter stimmen nicht überein.';
      return;
    }

    if (this.password.length < 6) {
      this.error = 'Passwort muss mindestens 6 Zeichen lang sein.';
      return;
    }

    this.submitting = true;
    this.error = null;

    this.authService.register(this.name, this.email, this.password).subscribe({
      next: (response) => {
        if (response.success) {
          this.registerSuccess.emit();
        } else {
          this.error = response.message;
        }
        this.submitting = false;
      },
      error: (error) => {
        console.error('Registrierungs-Fehler:', error);
        this.error = error.error?.message || 'Registrierung fehlgeschlagen. Bitte versuche es erneut.';
        this.submitting = false;
      }
    });
  }

  onClose() {
    this.close.emit();
  }

  onSwitchToLogin() {
    this.switchToLogin.emit();
  }

  onBackdropClick(event: MouseEvent) {
    if (event.target === event.currentTarget) {
      this.onClose();
    }
  }
}

<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50" (click)="onBackdropClick($event)">
  <div class="bg-white rounded-lg shadow-xl w-full max-w-md mx-4 p-8">
    <!-- Header -->
    <div class="flex justify-between items-center mb-6">
      <h2 class="text-2xl text-gray-900">Registrieren</h2>
      <button 
        (click)="onClose()"
        class="text-gray-400 hover:text-gray-600">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
        </svg>
      </button>
    </div>

    <!-- Error Message -->
    <div *ngIf="error" class="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg">
      <p class="text-sm text-red-800">{{ error }}</p>
    </div>

    <!-- Form -->
    <form (ngSubmit)="onSubmit()">
      <div class="mb-4">
        <label class="block text-sm text-gray-700 mb-2">Name</label>
        <input
          type="text"
          [(ngModel)]="name"
          name="name"
          required
          placeholder="Dein Name"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
      </div>

      <div class="mb-4">
        <label class="block text-sm text-gray-700 mb-2">E-Mail</label>
        <input
          type="email"
          [(ngModel)]="email"
          name="email"
          required
          placeholder="deine@email.com"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
      </div>

      <div class="mb-4">
        <label class="block text-sm text-gray-700 mb-2">Passwort</label>
        <input
          type="password"
          [(ngModel)]="password"
          name="password"
          required
          placeholder="Mindestens 6 Zeichen"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
      </div>

      <div class="mb-6">
        <label class="block text-sm text-gray-700 mb-2">Passwort wiederholen</label>
        <input
          type="password"
          [(ngModel)]="confirmPassword"
          name="confirmPassword"
          required
          placeholder="••••••••"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
      </div>

      <button
        type="submit"
        [disabled]="submitting"
        class="w-full px-6 py-3 bg-orange-600 text-white rounded-lg hover:bg-orange-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors mb-4">
        {{ submitting ? 'Wird registriert...' : 'Registrieren' }}
      </button>

      <p class="text-center text-sm text-gray-600">
        Bereits ein Konto?
        <button
          type="button"
          (click)="onSwitchToLogin()"
          class="text-orange-600 hover:text-orange-700 ml-1">
          Jetzt anmelden
        </button>
      </p>
    </form>
  </div>
</div>
