// src/components/UploadRecipe.tsx
import { useState, useRef } from 'react';
import { Upload, X, Plus, ArrowLeft } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Textarea } from './ui/textarea';
import { Card, CardContent, CardHeader } from './ui/card';
import { Label } from './ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { ImageWithFallback } from './figma/ImageWithFallback';
import type { User } from '../App';

type UploadRecipeProps = {
  currentUser: User;
  onCancel: () => void;
  onSuccess: () => void;
};

export function UploadRecipe({ currentUser, onCancel, onSuccess }: UploadRecipeProps) {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [cookTime, setCookTime] = useState('');
  const [difficulty, setDifficulty] = useState('');
  const [ingredients, setIngredients] = useState<string[]>(['']);
  const [instructions, setInstructions] = useState<string[]>(['']);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [isUploading, setIsUploading] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleImageChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // Validierung des Dateityps
      if (!file.type.startsWith('image/')) {
        alert('Bitte wähle eine Bilddatei aus');
        return;
      }

      // Validierung der Dateigröße (max 5MB)
      if (file.size > 5 * 1024 * 1024) {
        alert('Die Datei ist zu groß. Maximum 5MB.');
        return;
      }

      setImageFile(file);
      const reader = new FileReader();
      reader.onloadend = () => {
        setImagePreview(reader.result as string);
      };
      reader.readAsDataURL(file);
    }
  };

  const addIngredient = () => {
    setIngredients([...ingredients, '']);
  };

  const removeIngredient = (index: number) => {
    setIngredients(ingredients.filter((_, i) => i !== index));
  };

  const updateIngredient = (index: number, value: string) => {
    const newIngredients = [...ingredients];
    newIngredients[index] = value;
    setIngredients(newIngredients);
  };

  const addInstruction = () => {
    setInstructions([...instructions, '']);
  };

  const removeInstruction = (index: number) => {
    setInstructions(instructions.filter((_, i) => i !== index));
  };

  const updateInstruction = (index: number, value: string) => {
    const newInstructions = [...instructions];
    newInstructions[index] = value;
    setInstructions(newInstructions);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    // Validierung
    if (!title || !description || !cookTime || !difficulty) {
      alert('Bitte fülle alle Pflichtfelder aus');
      return;
    }

    if (!imageFile) {
      alert('Bitte füge ein Bild hinzu');
      return;
    }

    const validIngredients = ingredients.filter(i => i.trim() !== '');
    const validInstructions = instructions.filter(i => i.trim() !== '');

    if (validIngredients.length === 0 || validInstructions.length === 0) {
      alert('Bitte füge mindestens eine Zutat und einen Zubereitungsschritt hinzu');
      return;
    }

    setIsUploading(true);

    // Simuliert Ajax File Upload zum PHP Backend
    // In der echten Anwendung würde hier FormData mit fetch() gesendet werden
    const formData = new FormData();
    formData.append('image', imageFile);
    formData.append('title', title);
    formData.append('description', description);
    formData.append('cookTime', cookTime);
    formData.append('difficulty', difficulty);
    formData.append('ingredients', JSON.stringify(validIngredients));
    formData.append('instructions', JSON.stringify(validInstructions));
    formData.append('userId', currentUser.id.toString());

    console.log('Ajax FormData Upload würde an PHP Backend gesendet:');
    for (let [key, value] of formData.entries()) {
      console.log(key, value);
    }

    // Simuliert Upload-Verzögerung
    await new Promise(resolve => setTimeout(resolve, 2000));

    setIsUploading(false);
    alert('Rezept erfolgreich hochgeladen! 🎉');
    onSuccess();
  };

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <Button
        variant="ghost"
        onClick={onCancel}
        className="mb-6"
      >
        <ArrowLeft className="size-4 mr-2" />
        Abbrechen
      </Button>

      <Card>
        <CardHeader>
          <h1 className="text-orange-600">Neues Rezept hochladen</h1>
          <p className="text-gray-600">Teile dein Lieblingsrezept mit der Culina-Community</p>
        </CardHeader>
        <CardContent>
          <form onSubmit={handleSubmit} className="space-y-6">
            {/* Bild Upload */}
            <div>
              <Label htmlFor="image">Rezeptbild *</Label>
              <div className="mt-2">
                {imagePreview ? (
                  <div className="relative aspect-video rounded-lg overflow-hidden bg-gray-100">
                    <ImageWithFallback
                      src={imagePreview}
                      alt="Rezeptvorschau"
                      className="w-full h-full object-cover"
                    />
                    <button
                      type="button"
                      onClick={() => {
                        setImagePreview(null);
                        setImageFile(null);
                        if (fileInputRef.current) {
                          fileInputRef.current.value = '';
                        }
                      }}
                      className="absolute top-2 right-2 p-2 bg-red-500 text-white rounded-full hover:bg-red-600 transition-colors"
                    >
                      <X className="size-4" />
                    </button>
                  </div>
                ) : (
                  <div
                    onClick={() => fileInputRef.current?.click()}
                    className="border-2 border-dashed border-gray-300 rounded-lg p-12 text-center hover:border-orange-400 hover:bg-orange-50/50 transition-colors cursor-pointer"
                  >
                    <Upload className="size-12 mx-auto mb-4 text-gray-400" />
                    <p className="text-gray-600 mb-2">
                      Klicke hier oder ziehe ein Bild hierher
                    </p>
                    <p className="text-sm text-gray-500">
                      PNG, JPG bis zu 5MB
                    </p>
                  </div>
                )}
                <input
                  ref={fileInputRef}
                  id="image"
                  type="file"
                  accept="image/*"
                  onChange={handleImageChange}
                  className="hidden"
                />
              </div>
            </div>

            {/* Grundinformationen */}
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <Label htmlFor="title">Rezepttitel *</Label>
                <Input
                  id="title"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="z.B. Spaghetti Carbonara"
                  required
                />
              </div>

              <div>
                <Label htmlFor="cookTime">Zubereitungszeit *</Label>
                <Input
                  id="cookTime"
                  value={cookTime}
                  onChange={(e) => setCookTime(e.target.value)}
                  placeholder="z.B. 30 Min"
                  required
                />
              </div>
            </div>

            <div>
              <Label htmlFor="difficulty">Schwierigkeitsgrad *</Label>
              <Select value={difficulty} onValueChange={setDifficulty} required>
                <SelectTrigger>
                  <SelectValue placeholder="Wähle einen Schwierigkeitsgrad" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Einfach">Einfach</SelectItem>
                  <SelectItem value="Mittel">Mittel</SelectItem>
                  <SelectItem value="Schwer">Schwer</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <div>
              <Label htmlFor="description">Beschreibung *</Label>
              <Textarea
                id="description"
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Beschreibe dein Rezept..."
                rows={3}
                className="resize-none"
                required
              />
            </div>

            {/* Zutaten */}
            <div>
              <Label>Zutaten *</Label>
              <div className="space-y-2 mt-2">
                {ingredients.map((ingredient, index) => (
                  <div key={index} className="flex gap-2">
                    <Input
                      value={ingredient}
                      onChange={(e) => updateIngredient(index, e.target.value)}
                      placeholder={`Zutat ${index + 1}`}
                    />
                    {ingredients.length > 1 && (
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        onClick={() => removeIngredient(index)}
                      >
                        <X className="size-4" />
                      </Button>
                    )}
                  </div>
                ))}
                <Button
                  type="button"
                  variant="outline"
                  onClick={addIngredient}
                  className="w-full"
                >
                  <Plus className="size-4 mr-2" />
                  Zutat hinzufügen
                </Button>
              </div>
            </div>

            {/* Zubereitungsschritte */}
            <div>
              <Label>Zubereitungsschritte *</Label>
              <div className="space-y-2 mt-2">
                {instructions.map((instruction, index) => (
                  <div key={index} className="flex gap-2">
                    <div className="flex-shrink-0 w-8 h-8 rounded-full bg-gradient-to-br from-orange-500 to-amber-600 text-white flex items-center justify-center mt-2">
                      {index + 1}
                    </div>
                    <Textarea
                      value={instruction}
                      onChange={(e) => updateInstruction(index, e.target.value)}
                      placeholder={`Schritt ${index + 1}`}
                      rows={2}
                      className="resize-none flex-1"
                    />
                    {instructions.length > 1 && (
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        onClick={() => removeInstruction(index)}
                        className="mt-2"
                      >
                        <X className="size-4" />
                      </Button>
                    )}
                  </div>
                ))}
                <Button
                  type="button"
                  variant="outline"
                  onClick={addInstruction}
                  className="w-full"
                >
                  <Plus className="size-4 mr-2" />
                  Schritt hinzufügen
                </Button>
              </div>
            </div>

            {/* Submit Button */}
            <div className="flex gap-3 pt-6">
              <Button
                type="button"
                variant="outline"
                onClick={onCancel}
                className="flex-1"
              >
                Abbrechen
              </Button>
              <Button
                type="submit"
                disabled={isUploading}
                className="flex-1 bg-gradient-to-r from-orange-500 to-amber-600 hover:from-orange-600 hover:to-amber-700"
              >
                {isUploading ? (
                  <>
                    <div className="animate-spin rounded-full h-4 w-4 border-2 border-white border-t-transparent mr-2" />
                    Wird hochgeladen...
                  </>
                ) : (
                  <>
                    <Upload className="size-4 mr-2" />
                    Rezept veröffentlichen
                  </>
                )}
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
}

// src/angular-frontend/src/app/components/upload-recipe/upload-recipe.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { RecipeService } from '../../services/recipe.service';

@Component({
  selector: 'app-upload-recipe',
  templateUrl: './upload-recipe.component.html',
  styleUrls: ['./upload-recipe.component.css']
})
export class UploadRecipeComponent {
  @Output() recipeUploaded = new EventEmitter<void>();
  @Output() cancelClick = new EventEmitter<void>();

  title = '';
  description = '';
  cookTime = '';
  difficulty: 'Einfach' | 'Mittel' | 'Schwer' = 'Mittel';
  ingredients: string[] = [''];
  instructions: string[] = [''];
  selectedFile: File | null = null;
  previewUrl: string | null = null;
  submitting = false;

  constructor(private recipeService: RecipeService) {}

  onFileSelected(event: any) {
    const file = event.target.files[0];
    if (file) {
      this.selectedFile = file;
      
      // Bildvorschau erstellen
      const reader = new FileReader();
      reader.onload = (e: any) => {
        this.previewUrl = e.target.result;
      };
      reader.readAsDataURL(file);
    }
  }

  addIngredient() {
    this.ingredients.push('');
  }

  removeIngredient(index: number) {
    if (this.ingredients.length > 1) {
      this.ingredients.splice(index, 1);
    }
  }

  updateIngredient(index: number, value: string) {
    this.ingredients[index] = value;
  }

  addInstruction() {
    this.instructions.push('');
  }

  removeInstruction(index: number) {
    if (this.instructions.length > 1) {
      this.instructions.splice(index, 1);
    }
  }

  updateInstruction(index: number, value: string) {
    this.instructions[index] = value;
  }

  onSubmit() {
    // Validierung
    if (!this.title || !this.description || !this.cookTime || !this.selectedFile) {
      alert('Bitte fülle alle Pflichtfelder aus und wähle ein Bild aus.');
      return;
    }

    const filteredIngredients = this.ingredients.filter(i => i.trim() !== '');
    const filteredInstructions = this.instructions.filter(i => i.trim() !== '');

    if (filteredIngredients.length === 0 || filteredInstructions.length === 0) {
      alert('Bitte füge mindestens eine Zutat und eine Anweisung hinzu.');
      return;
    }

    // FormData erstellen
    const formData = new FormData();
    formData.append('title', this.title);
    formData.append('description', this.description);
    formData.append('cookTime', this.cookTime);
    formData.append('difficulty', this.difficulty);
    formData.append('ingredients', JSON.stringify(filteredIngredients));
    formData.append('instructions', JSON.stringify(filteredInstructions));
    formData.append('image', this.selectedFile);

    this.submitting = true;

    this.recipeService.createRecipe(formData).subscribe({
      next: (response) => {
        if (response.success) {
          alert('Rezept erfolgreich hochgeladen!');
          this.recipeUploaded.emit();
        }
        this.submitting = false;
      },
      error: (error) => {
        console.error('Fehler beim Hochladen:', error);
        alert(error.error?.message || 'Fehler beim Hochladen des Rezepts.');
        this.submitting = false;
      }
    });
  }

  onCancel() {
    this.cancelClick.emit();
  }
}

<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
  <div class="bg-white rounded-lg shadow-lg p-8">
    <h2 class="text-3xl text-gray-900 mb-8">Neues Rezept hochladen</h2>

    <form (ngSubmit)="onSubmit()">
      <!-- Titel -->
      <div class="mb-6">
        <label class="block text-sm text-gray-700 mb-2">Titel *</label>
        <input
          type="text"
          [(ngModel)]="title"
          name="title"
          required
          placeholder="z.B. Pasta Carbonara"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
      </div>

      <!-- Beschreibung -->
      <div class="mb-6">
        <label class="block text-sm text-gray-700 mb-2">Beschreibung *</label>
        <textarea
          [(ngModel)]="description"
          name="description"
          required
          rows="3"
          placeholder="Kurze Beschreibung des Rezepts"
          class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
        </textarea>
      </div>

      <!-- Kochzeit & Schwierigkeit -->
      <div class="grid grid-cols-2 gap-6 mb-6">
        <div>
          <label class="block text-sm text-gray-700 mb-2">Kochzeit *</label>
          <input
            type="text"
            [(ngModel)]="cookTime"
            name="cookTime"
            required
            placeholder="z.B. 30 Min"
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
        </div>

        <div>
          <label class="block text-sm text-gray-700 mb-2">Schwierigkeit *</label>
          <select
            [(ngModel)]="difficulty"
            name="difficulty"
            required
            class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
            <option value="Einfach">Einfach</option>
            <option value="Mittel">Mittel</option>
            <option value="Schwer">Schwer</option>
          </select>
        </div>
      </div>

      <!-- Bild-Upload -->
      <div class="mb-6">
        <label class="block text-sm text-gray-700 mb-2">Bild *</label>
        <div class="border-2 border-dashed border-gray-300 rounded-lg p-6 text-center">
          <input
            type="file"
            (change)="onFileSelected($event)"
            accept="image/*"
            class="hidden"
            #fileInput>
          
          <div *ngIf="!previewUrl">
            <svg class="w-12 h-12 text-gray-400 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" 
                    d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z">
              </path>
            </svg>
            <button
              type="button"
              (click)="fileInput.click()"
              class="px-4 py-2 bg-orange-600 text-white rounded-lg hover:bg-orange-700">
              Bild auswählen
            </button>
          </div>

          <div *ngIf="previewUrl" class="relative">
            <img [src]="previewUrl" alt="Vorschau" class="max-h-64 mx-auto rounded-lg">
            <button
              type="button"
              (click)="previewUrl = null; selectedFile = null"
              class="absolute top-2 right-2 bg-red-600 text-white rounded-full p-2 hover:bg-red-700">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
              </svg>
            </button>
          </div>
        </div>
      </div>

      <!-- Zutaten -->
      <div class="mb-6">
        <div class="flex justify-between items-center mb-2">
          <label class="block text-sm text-gray-700">Zutaten *</label>
          <button
            type="button"
            (click)="addIngredient()"
            class="text-sm text-orange-600 hover:text-orange-700">
            + Zutat hinzufügen
          </button>
        </div>
        <div class="space-y-2">
          <div *ngFor="let ingredient of ingredients; let i = index" class="flex gap-2">
            <input
              type="text"
              [value]="ingredient"
              (input)="updateIngredient(i, $any($event.target).value)"
              placeholder="z.B. 400g Spaghetti"
              class="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
            <button
              type="button"
              (click)="removeIngredient(i)"
              [disabled]="ingredients.length === 1"
              class="px-3 py-2 bg-red-100 text-red-600 rounded-lg hover:bg-red-200 disabled:opacity-50 disabled:cursor-not-allowed">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
              </svg>
            </button>
          </div>
        </div>
      </div>

      <!-- Anweisungen -->
      <div class="mb-8">
        <div class="flex justify-between items-center mb-2">
          <label class="block text-sm text-gray-700">Zubereitungsschritte *</label>
          <button
            type="button"
            (click)="addInstruction()"
            class="text-sm text-orange-600 hover:text-orange-700">
            + Schritt hinzufügen
          </button>
        </div>
        <div class="space-y-2">
          <div *ngFor="let instruction of instructions; let i = index" class="flex gap-2">
            <span class="flex-shrink-0 w-8 h-8 bg-orange-600 text-white rounded-full flex items-center justify-center mt-2">
              {{ i + 1 }}
            </span>
            <textarea
              [value]="instruction"
              (input)="updateInstruction(i, $any($event.target).value)"
              rows="2"
              placeholder="Beschreibe diesen Zubereitungsschritt"
              class="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent">
            </textarea>
            <button
              type="button"
              (click)="removeInstruction(i)"
              [disabled]="instructions.length === 1"
              class="px-3 py-2 bg-red-100 text-red-600 rounded-lg hover:bg-red-200 disabled:opacity-50 disabled:cursor-not-allowed self-start mt-2">
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
              </svg>
            </button>
          </div>
        </div>
      </div>

      <!-- Buttons -->
      <div class="flex gap-4">
        <button
          type="submit"
          [disabled]="submitting"
          class="flex-1 px-6 py-3 bg-orange-600 text-white rounded-lg hover:bg-orange-700 disabled:bg-gray-300 disabled:cursor-not-allowed transition-colors">
          {{ submitting ? 'Wird hochgeladen...' : 'Rezept veröffentlichen' }}
        </button>
        <button
          type="button"
          (click)="onCancel()"
          [disabled]="submitting"
          class="px-6 py-3 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300 transition-colors">
          Abbrechen
        </button>
      </div>
    </form>
  </div>
</div>
